/*
    example_vco_ringmod.cpp — AnalogVCO + RingModulator sample
    ============================================================
    Combine a carrier generated by AnalogVCO with the input signal via a ring modulator.
    An example of modular-style patching similar to SuperCollider / Max/MSP.

        1. VCO Saw → RingMod (classic ring modulation)
        2. VCO Pulse (PWM) → RingMod (square carrier for bell-like tones)
        3. VCO Tri + Ge diode → RingMod (warm ring modulation)

    Build:
        c++ -std=c++17 -O2 -I.. example_vco_ringmod.cpp -o example_vco_ringmod
*/

#include "include/patina.h"
#include "examples/wav_writer.h"

#include <cstdio>
#include <cmath>
#include <vector>

int main()
{
    constexpr int   kSampleRate   = 48000;
    constexpr int   kChannels     = 2;
    constexpr float kDurationSec  = 9.0f;  // 3 sec × 3 sections
    constexpr int   kTotalSamples = (int)(kSampleRate * kDurationSec);

    // Construct VCO (carrier generator) and RingModulator independently
    AnalogVCO vco;
    RingModulator ringMod;

    patina::ProcessSpec spec{(double)kSampleRate, 256, kChannels};
    vco.prepare(spec);
    ringMod.prepare(spec);

    // Input signal: 330Hz (E) sine burst
    auto testSignal = wav::sineBurst(kSampleRate, 330.0f, kDurationSec, 0.5f, 60.0f, 300.0f);

    std::vector<std::vector<float>> output(kChannels,
        std::vector<float>((size_t)kTotalSamples, 0.0f));

    const int segmentLen = kTotalSamples / 3;

    // ===== Section 1: Saw VCO (500 Hz) × Input =====
    {
        std::printf("  Section 1: Saw VCO (500 Hz) x Input — Si diode bridge\n");
        vco.reset();
        ringMod.reset();

        AnalogVCO::Spec vcoSpec;
        vcoSpec.freqHz    = 500.0;
        vcoSpec.waveform  = 0;  // Saw
        vcoSpec.drift     = 0.001;

        RingModulator::Params rmParams;
        rmParams.mix       = 0.8f;
        rmParams.diodeType = 0;  // Si
        rmParams.mismatch  = 0.02f;

        for (int i = 0; i < segmentLen; ++i)
        {
            float carrier = vco.process(0, vcoSpec);
            float in = testSignal[(size_t)i];
            float out = ringMod.process(0, in, carrier, rmParams);
            output[0][(size_t)i] = out;
            output[1][(size_t)i] = out;
        }
    }

    // ===== Section 2: Pulse VCO (800 Hz, PWM) × Input =====
    {
        std::printf("  Section 2: Pulse VCO (800 Hz, PWM) x Input — Schottky bridge\n");
        vco.reset();
        ringMod.reset();

        AnalogVCO::Spec vcoSpec;
        vcoSpec.freqHz     = 800.0;
        vcoSpec.waveform   = 2;  // Pulse
        vcoSpec.pulseWidth = 0.3;
        vcoSpec.drift      = 0.002;

        RingModulator::Params rmParams;
        rmParams.mix       = 1.0f;
        rmParams.diodeType = 1;  // Schottky
        rmParams.mismatch  = 0.05f;

        const int start = segmentLen;
        const int end   = segmentLen * 2;
        for (int i = start; i < end; ++i)
        {
            float carrier = vco.process(0, vcoSpec);
            float in = testSignal[(size_t)i];
            float out = ringMod.process(0, in, carrier, rmParams);
            output[0][(size_t)i] = out;
            output[1][(size_t)i] = out;
        }
    }

    // ===== Section 3: Tri VCO (300 Hz) × Input — Ge warm ring =====
    {
        std::printf("  Section 3: Tri VCO (300 Hz) x Input — Ge diode bridge\n");
        vco.reset();
        ringMod.reset();

        AnalogVCO::Spec vcoSpec;
        vcoSpec.freqHz     = 300.0;
        vcoSpec.waveform   = 1;  // Tri
        vcoSpec.temperature = 30.0;
        vcoSpec.drift      = 0.003;  // vintage-style drift

        RingModulator::Params rmParams;
        rmParams.mix         = 0.7f;
        rmParams.diodeType   = 2;  // Ge
        rmParams.mismatch    = 0.08f;  // 大きめのミスマッチでキャリア漏れ多め
        rmParams.temperature = 30.0f;

        const int start = segmentLen * 2;
        for (int i = start; i < kTotalSamples; ++i)
        {
            float carrier = vco.process(0, vcoSpec);
            float in = testSignal[(size_t)i];
            float out = ringMod.process(0, in, carrier, rmParams);
            output[0][(size_t)i] = out;
            output[1][(size_t)i] = out;
        }
    }

    if (wav::write("output_vco_ringmod.wav", output, kSampleRate))
        std::printf("=> output_vco_ringmod.wav written (%d samples, %.1f sec)\n",
                    kTotalSamples, kDurationSec);
    else
        std::printf("ERROR: failed to write WAV\n");

    return 0;
}
